image:
  # x-release-please-start-version
  lfaiAPITag: 0.7.2
  # x-release-please-end
  kiwigridTag: 1.23.3

supabase:
  url: "###ZARF_VAR_SUPABASE_CLUSTER_URL###"

api:
  replicas: 1
  port: 8080
  exposeOpenAPISchema: false
  defaultEmbeddingsModel: "###ZARF_VAR_DEFAULT_EMBEDDINGS_MODEL###"

package:
  host: leapfrogai-api
